# This file has been autogenerated. Do not change by hand. 

#' Create a parameter object for the function runSelfControlledCohort
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param firstOccurrenceDrugOnly          If TRUE, only use first occurrence of each drug concept
#'                                         idfor each person
#' @param firstOccurrenceConditionOnly     If TRUE, only use first occurrence of each condition
#'                                         conceptid for each person.
#' @param outcomeConditionTypeConceptIds   A list of TYPE_CONCEPT_ID values that will restrictcondition
#'                                         occurrences.  Only applicable if outcomeTable
#'                                         =CONDITION_OCCURRENCE.
#' @param genderConceptIds                 of gender_concept_id, generally use MALE (8507) and
#'                                         FEMALE(8532).
#' @param minAge                           Integer for minimum allowable age.
#' @param maxAge                           Integer for maximum allowable age.
#' @param studyStartDate                   Date for minimum allowable data for index exposure.
#' @param studyEndDate                     Date for maximum allowable data for index exposure.
#' @param stratifyByGender                 If TRUE, analysis will be calculated overall, and
#'                                         stratifiedacross all gender groups.
#' @param stratifyByAge                    If TRUE, analysis will be calculated overall, and
#'                                         stratifiedacross all age groups (using AGE_GROUP table
#'                                         below).
#' @param stratifyByYear                   If TRUE, analysis will be calculated overall, and
#'                                         stratifiedacross all years of the index dates.
#' @param useLengthOfExposureExposed       If TRUE, use the duration from drugEraStart -> drugEraEnd
#'                                         aspart of timeAtRisk.
#' @param timeAtRiskExposedStart           Integer of days to add to drugEraStart for start
#'                                         oftimeAtRisk (0 to include index date, 1 to start the
#'                                         dayafter).
#' @param surveillanceExposed              Additional window to add to end of exposure period
#'                                         (ifuseLengthOfExposureExposed = TRUE, then add to exposure
#'                                         enddate, else add to exposure start date).
#' @param useLengthOfExposureUnexposed     If TRUE, use the duration from exposure start -> exposureend
#'                                         as part of timeAtRisk looking back before exposurestart.
#' @param timeAtRiskUnexposedStart         Integer of days to add to exposure start for start
#'                                         oftimeAtRisk (0 to include index date, -1 to start the
#'                                         daybefore).
#' @param surveillanceUnexposed            Additional window to add to end of exposure period
#'                                         (ifuseLengthOfExposureUnexposed = TRUE, then add to
#'                                         exposureend date, else add to exposure start date).
#' @param hasFullTimeAtRisk                If TRUE, restrict to people who have full
#'                                         time-at-riskexposed and unexposed.
#' @param washoutWindow                    Integer to define required time observed before
#'                                         exposurestart.
#' @param followupWindow                   Integer to define required time observed after
#'                                         exposurestart.
#' @param shrinkage                        Shrinkage used in IRR calculations, required >0 to deal
#'                                         with0 case counts, but larger number means more shrinkage.
#'
#' @export
createRunSelfControlledCohortArgs <- function(firstOccurrenceDrugOnly = TRUE,
                                              firstOccurrenceConditionOnly = TRUE,
                                              outcomeConditionTypeConceptIds = c(38000247),
                                              genderConceptIds = c(8507, 8532),
                                              minAge = "",
                                              maxAge = "",
                                              studyStartDate = "",
                                              studyEndDate = "",
                                              stratifyByGender = FALSE,
                                              stratifyByAge = FALSE,
                                              stratifyByYear = FALSE,
                                              useLengthOfExposureExposed = TRUE,
                                              timeAtRiskExposedStart = 1,
                                              surveillanceExposed = 30,
                                              useLengthOfExposureUnexposed = TRUE,
                                              timeAtRiskUnexposedStart = -1,
                                              surveillanceUnexposed = -30,
                                              hasFullTimeAtRisk = FALSE,
                                              washoutWindow = 0,
                                              followupWindow = 0,
                                              shrinkage = 1e-04) {
  analysis <- OhdsiRTools::convertArgsToList(match.call(), "args")
  return(analysis)
}
